### ISSUE TITLE
Milestone 5 - Project Documentation Updates

### ISSUE THREAD

**Issue by DanielCender** [DanielCender/CST-247-CLC#19]
### Work
---
- [ ] Updated Sprint Product Log
- [ ] Updated Sprint Back Log
- [ ] Updated Sprint Burn Down Chart
- [ ] Results of Scrum Retrospective (in the Design Report).
- [ ] Final Design Report (with ER diagram, Class diagrams, Flow Charts, etc.)
- [ ] All code artifacts and design artifacts (with GIT URL's to the above planning artifacts) checked into the GIT Repository
